
# Application name
spring.application.name=ecommerce.inventory.management

# Server port
server.port=8081

# =====================
# PRODUCTION DATABASE - PostgreSQL (commented for dev/test)
#=====================
 spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_inventory
 spring.datasource.username=postgres
 spring.datasource.password=1234
 spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =====================
# DEVELOPMENT/TEST - H2 in-memory DB
# =====================
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# =====================
# Redis Cache
# =====================
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

# =====================
# Logging
# =====================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# =====================
# Optional: To Disable Devtools Restart Warning
# =====================
spring.devtools.restart.enabled=false

